# Generated by Django 4.2.4 on 2023-08-09 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=100, verbose_name='Наименование раздела')),
            ],
            options={
                'verbose_name': 'Разделы',
                'verbose_name_plural': 'Раздел',
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Города',
                'verbose_name_plural': 'Город',
            },
        ),
        migrations.CreateModel(
            name='CompanyOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Тип регистрации')),
            ],
            options={
                'verbose_name': 'Компания или Подрядчик',
                'verbose_name_plural': 'Компания или Подрядчик',
            },
        ),
        migrations.CreateModel(
            name='Job_Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=255, verbose_name='Вид работы')),
                ('chapter_foreignkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.chapter', verbose_name='какому разделу относитя')),
            ],
            options={
                'verbose_name': 'Виды работ',
                'verbose_name_plural': 'Работа',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organization', models.CharField(max_length=50, verbose_name='Наименование Организации')),
                ('Iin', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='БИН или ИИН компании')),
                ('Director', models.CharField(max_length=255, verbose_name='ФИО директора полностью')),
                ('Number1', models.CharField(max_length=11, verbose_name='Контактные данные')),
                ('Finished_project', models.TextField(verbose_name='Ваши завершенные проекты')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Ваши Комерческое предложение')),
                ('consideration', models.CharField(max_length=10, verbose_name='Рассмартирваете работать в разных городах?')),
                ('Job1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.job_chapter', verbose_name='Виды работ')),
                ('TOO_IP', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.companyorganization', verbose_name='Тип')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.cities', verbose_name='Ваш город')),
            ],
            options={
                'verbose_name': 'Подрядные организации',
                'verbose_name_plural': 'Данные подрядных организации',
            },
        ),
    ]
