# Generated by Django 4.2.4 on 2023-08-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='test',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='test'),
        ),
    ]
