# Generated by Django 4.2.4 on 2023-08-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_organization_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='file',
            field=models.FileField(blank=True, default='media/Книга2.xlsx', null=True, upload_to='media/', verbose_name='Ваши Комерческое предложение'),
        ),
    ]
