# Generated by Django 4.2.4 on 2023-08-18 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_organization_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, verbose_name='статус подписки')),
            ],
            options={
                'verbose_name': 'Статус подписки',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.AlterField(
            model_name='organization',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Ваши Комерческое предложение'),
        ),
        migrations.AddField(
            model_name='organization',
            name='status_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.status_account', verbose_name='Статус подписки'),
        ),
    ]
