# Generated by Django 4.2.4 on 2023-08-18 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_status_account_alter_organization_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='status_account',
            field=models.ForeignKey(blank=True, default='Без подписки', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.status_account', verbose_name='Статус подписки'),
        ),
    ]
