# Generated by Django 4.2.4 on 2023-08-30 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_organization_status_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raiting_choice', models.CharField(default='0', max_length=3, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Рейтинги',
                'verbose_name_plural': 'Рейтинг',
            },
        ),
        migrations.AlterField(
            model_name='organization',
            name='Finished_project',
            field=models.TextField(verbose_name='Ваши завершенные проекты и описание компании'),
        ),
        migrations.AddField(
            model_name='organization',
            name='raiting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.raiting', verbose_name='Рейтинг'),
        ),
    ]
