# Generated by Django 4.2.4 on 2023-08-30 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_organization_status_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='status_account',
            field=models.ForeignKey(default='Без подписки', on_delete=django.db.models.deletion.CASCADE, to='product.status_account', verbose_name='Статус подписки'),
        ),
    ]
